apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gauzian-dev

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.enc.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - minio-pvc.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - front-deployment.yaml
  - front-service.yaml
  - middleware.yaml
  - ingressroute.yaml
