apiVersion: ENC[AES256_GCM,data:k1Q=,iv:e/TujEea8J8a9neyN81I+Kb9+TxZzOIMtQyuujV3OrM=,tag:P5ZCZv0b4cQNKVMxCUz4YQ==,type:str]
kind: ENC[AES256_GCM,data:VliaxhfG,iv:hiostWP4JQZprM6dy1vCslXpYRoLTmfuwGcwNpVO4YA=,tag:QMEpg/f4pXQ/ypbCBcIIUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VN/0vWzMa+asZ40K4CzK,iv:43/Wgg2YOHGBb8vF0ZOQserOqewYFGMhpDRYxXaBKLs=,tag:CMxEe+vbCEJhbxcgbtq3HQ==,type:str]
    namespace: ENC[AES256_GCM,data:QIYxrQPo43aGGw==,iv:tTN2qM9zxSW1yEMIlKbQ2ImTYbgHhrgmbbW8C2hgWGM=,tag:0jKInRht3HZ6YnW1mEpKbQ==,type:str]
type: ENC[AES256_GCM,data:EygRk/yF,iv:cKmlmAfJ6FK8a/3epLZjykCRowsqCx8DU1Ke64P0J6E=,tag:M7bqLbIdm9E/OCMVBFjtBQ==,type:str]
data:
    DB_USER: ENC[AES256_GCM,data:h91fYbFOXSQ=,iv:/8wB2xN1hQzXoHw5ltuHDX2bZ6X6mPAMk4v4ZTsP9S0=,tag:pMpqmwfqDDJOfdrUNCAgiw==,type:str]
    DB_NAME: ENC[AES256_GCM,data:CjZKG7Hyh/6FfUPs,iv:aDMi0MJofP8+QopSZb1VXBqW3E8nzNnUkbWNvogib40=,tag:KIq9o6yDwemKQ0b0x9vKzw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:G6qjTSoONVGTG/23Qx1njEourB6RBgBsb3w/41npM2JGEFrsGFursdh5yZQ=,iv:2JT0DePHAIM3BKNrAmZeUT5RmXJ3aJuWV5Ua223U3C0=,tag:6w8hy/i9UpGCLLB+U4FSeA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:b8JxJVQx/LZnvl7u7l47SQIAHjqvX9wcusOz/gS65cLIbgbj0D3dUeczZ2/Lwu1ffpdqvS+jYfHJNhLfTQVTpXC8/yuNy9+4H7G9ooBwwTbs7bqeXLquXw==,iv:Vzcv3++tLktsRcODVUiBx2p3Mv/niLR0n1jEn8lQiPU=,tag:FHo2E3WdOdiWP8OZ1GM3kQ==,type:str]
    REDIS_PASSWORD: ENC[AES256_GCM,data:XWHH0LcE5Oe8edJHQ7ZHr9mmCKuLKESMvwOGkMwZrNEJHtZLnKahYA==,iv:PKlQxo8NHtoLJIg4nI3DU2W8l7CpwoSRGQ4hj/D3MPo=,tag:DTm0lCaoxRIQT1vuGdIXyQ==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:6fF1lurD+PkFcowl6VU5X40+o/KTXbA2Im1Z3YDrYtcj0xrKthGaN9DkQYTvND5AftaU9mM6hZfa4aPP85eJ/Jq2FGA=,iv:+f2JFEZ6VQCUb4SUpiEk518QKYcBC77lu+FzGYHve1s=,tag:BO6ndWNy8HKzv1ba7/A8vw==,type:str]
    MINIO_ROOT_USER: ENC[AES256_GCM,data:/jTiU4K0lz0mtWBv0PE4vg==,iv:mqG2YCat2Xe9JtHCpwAnDZLou4Klky2o9GGLOP+yw4A=,tag:qZ78j52ZABDFmh9ygTDqQw==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:46HUKkdDOuKx3xAWnxdJx+BYMt+b0IJAYxQtUFnTG8nljoAXdyh753c8Jsc=,iv:5c2urPAzb6JxoJQo8aNF3Y9lRkGpnbEd71mqU5OGOm4=,tag:yZNYfyLtitDyLIPBTZRwbA==,type:str]
    S3_BUCKET: ENC[AES256_GCM,data:Uz1L1u/fawkHcfmJ,iv:aG1NA+sTaQ18kHUe03b3zB5QTOwwnIZQ452k//zmmps=,tag:nYx3ChaEVb06GfqMPgUbNQ==,type:str]
    MINIO_BROWSER_REDIRECT_URL: ENC[AES256_GCM,data:FN4kaTlgvMtYyqe2sdQbxn+v4NuKWYRFB4iQ2QDVifQobOoyz3Nuaw==,iv:vkJWARBSmjY9CRwrLFrUG0l8GZiMVc5i2JgKzGdCGpY=,tag:mWbN/HDN47Wa7eJq8ZqcZQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:XfKtGHuPpxhiy74SbLVR20i+iadNjJwonrDGWp6BAopIDU+F+lLFOH9SeEGxwAyB/a/QFNTcZwk/InzW9qSQd6uKK4IV0umITqWuetPKHY2stmBt,iv:aI5N418ShQztswr3yUzmId+ybZFBX9xkGkbM8H3HYcE=,tag:ZKqhrA/gNQOgwReeml/GJA==,type:str]
    METRICS_SECRET: ENC[AES256_GCM,data:AfYUWHtfbC8edElTLzXyISbncbWimDhlJjYGkfOSWAepLzPvWOeMf+kbM185omlccA8Up6J02o0=,iv:gbGj0YqpawAxUHZW2YJBNWs2W3cQmyiPkhA6NAYCHlg=,tag:WPGBKyCoa9RjweU/s8zTSQ==,type:str]
    SMTP_PASSWORD: ENC[AES256_GCM,data:s+LVjuLBgcXG8r/4brMIsUUdiLxOhiNnoFkKQMyZNAhD6Xt1oyYQMHFdwYA5FJRp,iv:vKZbDnUvNdBFJRQnOo99NPOZeJE2efzegcNpOevH5DQ=,tag:ru1AeWtCgnUJQym/fJBmdg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1xcm4yhupmd4krp7h0kt25ygxq8zsl452de87ndjujy2nf6sz3saq2e3den
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0ZVdXM0ZzZTFiUDZwRWtG
            NWFyd2xoak5BZDJGbXl0WEJvbGxBWGRjSHd3CkpRU043dHVzY2dxTmFESUVFWEp2
            c2d1UDBrQmdERlJiVGxxeTRLSE9jckkKLS0tIE1WajgxTGNuNXM2SjNzU1BMeVJn
            NkhQS1pJRzZ1bUdWRi9hUVVOaFBxRTAKsI9TXhb5lJp/e7CFKN5wXvIW+iP0XKoY
            ABQnkX1PPhTw9qPFq5IYI7ei6EjKYkgytU1+Wz2pHyX8rwhtDX/VWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T12:05:07Z"
    mac: ENC[AES256_GCM,data:l29h051nLg+CKEaeh8hXeQanqNIug5gqV+sZqQI5gbpIt5CJQYv2cz5j93CJKnwvHEU2U1pHoWzBEdujHMa6PK8b1qCvAMOxrqRndyE0ekL1nT6uZUi/BYLLV9p728cSw3R/i5CIjwaGh8BOnF8x0kLyVNxpQCeK5JDievw0RBY=,iv:R06E66v1CTOHy3i+22JdGj3Or3GQfAHRrJdxGGDFDXE=,tag:jVt7qCCa5gGCcb1sQrbTFw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.4
