apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monolith
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
  namespaceSelector:
    matchNames:
      - gauzian
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
      scrapeTimeout: 8s  # Doit Ãªtre < interval
