[package]
name = "gauzian_core"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7", features = ["postgres", "macros", "uuid", "time", "chrono", "ipnetwork"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }